[advisories]
ignore = []

[licenses]
allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "bzip2-1.0.6",
    "CC0-1.0",
    "ISC",
    "MIT",
    "OpenSSL",
    "Unicode-3.0",
    "Zlib",
]

[[licenses.clarify]]
name = "ring"
version = "*"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]

[sources]
unknown-registry = "deny"

