name: "Clean-up Disk Space"
description: "Remove unnecessary tools and clean up disk space on GitHub Actions runner."

runs:
  using: "composite"
  steps:
    - run: |
        # Remove .NET SDKs
        sudo rm -rf /usr/share/dotnet
        
        # Remove Swift toolchain
        sudo rm -rf /usr/share/swift
        
        # Remove Haskell (GHC)
        sudo rm -rf /usr/local/.ghcup
        
        # Remove Julia
        sudo rm -rf /usr/local/julia*
        
        # Remove Android SDKs
        sudo rm -rf /usr/local/lib/android
        
        # Remove Chromium (optional if not using for browser tests)
        sudo rm -rf /usr/local/share/chromium
        
        # Remove Microsoft/Edge and Google Chrome builds
        sudo rm -rf /opt/microsoft /opt/google
        
        # Remove Azure CLI
        sudo rm -rf /opt/az
        
        # Remove PowerShell
        sudo rm -rf /usr/local/share/powershell
        
        # Remove CodeQL and other toolcaches
        sudo rm -rf /opt/hostedtoolcache
        
        docker system prune -af || true
        docker builder prune -af || true
        df -h
      shell: bash